export const CLICK_UPDATE_SHOPPING_CART = 'CLICK_UPDATE_SHOPPING_CART';

export const GET_UPDATE_PRODUCTS = 'GET_UPDATE_PRODUCTS';

export const GET_PURCHASED_PRODUCTS = 'GET_PURCHASED_PRODUCTS';

export const CLOSE_BUTTON_SHOPPING_CART = 'CLOSE_BUTTON_SHOPPING_CART';